/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Inquiry {
  'id' : bigint,
  'relationshipPerson2Dob' : [] | [string],
  'relationshipPerson2Tob' : [] | [string],
  'dob' : string,
  'tob' : string,
  'palmPhotos' : Array<[] | [ExternalBlob]>,
  'serviceType' : bigint,
  'birthState' : [] | [string],
  'relationshipPerson2Name' : [] | [string],
  'question' : string,
  'birthCity' : [] | [string],
  'seedNumber' : [] | [bigint],
  'submittedAt' : Time,
  'birthCountry' : [] | [string],
  'handPictureBlob' : [] | [ExternalBlob],
  'visitorName' : string,
  'pastLifeNotes' : string,
}
export interface Post {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'published' : boolean,
  'createdAt' : Time,
  'author' : string,
}
export interface Service {
  'id' : bigint,
  'fee' : bigint,
  'name' : string,
  'description' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAdmin' : ActorMethod<[], boolean>,
  'createPost' : ActorMethod<[string, string, string], bigint>,
  'deleteInquiry' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllPostsAdmin' : ActorMethod<[], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishPost' : ActorMethod<[bigint, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitInquiry' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      [] | [ExternalBlob],
      Array<[] | [ExternalBlob]>,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
    ],
    bigint
  >,
  'updatePost' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
